"""'createtable'

Revision ID: 4b0a107afd4
Revises: None
Create Date: 2016-07-27 11:10:26.058854

"""

# revision identifiers, used by Alembic.
revision = '4b0a107afd4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qingsongyike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('docid', sa.String(length=32), nullable=True),
    sa.Column('ptime', sa.String(length=32), nullable=True),
    sa.Column('cover_img', sa.String(length=512), nullable=True),
    sa.Column('url_3g', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('docid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qingsongyike')
    ### end Alembic commands ###
